/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sac_sistema_administrador_de_condominios.Interfaces;

import Controllers.ControllerWindows;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Dany-PC
 */
public class Load_Windows_Interfaz extends javax.swing.JFrame implements Runnable {
    private static final Logger LOG = Logger.getLogger(Load_Windows_Interfaz.class.getName());
    private static final long serialVersionUID = 2012201552509950L;
    private Thread loading;
    private static String a[] = {"Inicioando Librerias", "Cargando Imagen", "Localizando Perfil", "Verificado Memoria", "Estructurando Algoritmo", "Instalando Algoritmos ", "Creacion de Pantalla",
        "Manejo se Pizarra", "Verificando Hadwared", "Hadwared Verificados", "Lidrerias Actualizadas", "Imagen Previa", "Pefiles de Inicio Cargados", "Memoria Establecida",
        "Algoritmos Listos", "Pizarra Completa y Lista", "Iniciando Programa", "Ultima Verificacion", "Verificando", "Iniciado Ventana Principal", "Inicio Terminado", "Bienvenido"};
    private static String b[] = {"Cargando...", "Cargando..", "Cargando.", "Cargando..", "Cargando...", "Cargando..", "Cargando.", "Cargando..", "Cargando...", "Cargando..",
        "Cargando.", "Cargando..", "Cargando...", "Cargando..", "Cargando.", "Cargando..", "Cargando...", "Cargando..", "Cargando.", "Cargando..", "Cargando...",
        "Cargando.."};

    /**
     * Creates new form Load_Windows_Interfaz
     */
    public Load_Windows_Interfaz() {
        initComponents();
        setLocationRelativeTo(null);
    }

    public void run() {
        int num = 0, num1 = 0;
        while (num < 2000) {
            try {
                this.setVisible(true);
                loadingBar.setValue(num);
                loadingBar.repaint();
                text2.setText(a[num1]);
                text1.setText(b[num1]);
                loading.sleep(300);
            } catch (InterruptedException ex) {
                Logger.getLogger(Load_Windows_Interfaz.class.getName()).log(Level.SEVERE, "Error de Ejeccion de la ventana de Carga");
            }
            num += 95;
            num1++;
        }
        this.dispose();
        Windows_Interfaz view = new Windows_Interfaz();
        ControllerWindows controller = new ControllerWindows(view);
        view.controller(controller);
        view.setVisible(true);
    }

    @Override
    public String toString() {

        return "Created by FL- AndruAnnohomy smart pataforma: Load_Window_FL_LAII{" + '}';

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        text1 = new javax.swing.JLabel();
        text2 = new javax.swing.JLabel();
        loadingBar = new javax.swing.JProgressBar(0,2000);
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Corbel", 1, 90)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("SAC");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 180, 80));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Sistemas Administrador de Condominios");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 290, -1));

        text1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        text1.setForeground(new java.awt.Color(255, 0, 51));
        text1.setText("Cargando..");
        getContentPane().add(text1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 80, -1));

        text2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        text2.setForeground(new java.awt.Color(255, 0, 51));
        text2.setText("y");
        getContentPane().add(text2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 280, -1));

        loadingBar.setBackground(new java.awt.Color(0, 0, 0));
        loadingBar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        loadingBar.setForeground(new java.awt.Color(0, 0, 0));
        loadingBar.setToolTipText("");
        loadingBar.setStringPainted(true);
        getContentPane().add(loadingBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 510, 20));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image_SAC_Manager/1.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    public static javax.swing.JProgressBar loadingBar;
    private javax.swing.JLabel text1;
    private javax.swing.JLabel text2;
    // End of variables declaration//GEN-END:variables
}
