/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sac_sistema_administrador_de_condominios.Interfaces;

import Codes.MySQL.MySQL;
import Controllers.ControllerResident;
import Extras.Letter_Mayus;
import Extras.only_letters;
import Extras.only_num;
import Extras.space_Letters;

/**
 *
 * @author Dany-PC
 */
public class Load_Residentes extends javax.swing.JFrame {

    public MySQL mysql;

    /**
     * Creates new form Load_Residentes
     */
    public Load_Residentes(MySQL mysql) {
        this.mysql = mysql;
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nom = new javax.swing.JTextField();
        FN = new com.toedter.calendar.JDateChooser();
        T_TEL = new javax.swing.JTextField();
        TEL1 = new javax.swing.JLabel();
        dir = new javax.swing.JTextField();
        Genero = new javax.swing.JComboBox();
        APP = new javax.swing.JTextField();
        F_N1 = new javax.swing.JLabel();
        APM = new javax.swing.JTextField();
        NOMBRE1 = new javax.swing.JLabel();
        NOMBRE = new javax.swing.JLabel();
        AP = new javax.swing.JLabel();
        AM = new javax.swing.JLabel();
        F_N = new javax.swing.JLabel();
        TEL = new javax.swing.JLabel();
        EMAIL = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        pass = new javax.swing.JPasswordField();
        EMAIL1 = new javax.swing.JLabel();
        Num_cas = new javax.swing.JTextField();
        Guardar = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ingresar Usuario");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del usuario"));

        nom.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        FN.setDateFormatString("yyyy-MM-d");

        T_TEL.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        TEL1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        TEL1.setText("Género:");

        dir.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        Genero.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "M", "F" }));

        APP.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        F_N1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        F_N1.setText("Apellido M:");

        APM.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        NOMBRE1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        NOMBRE1.setText("Password:");

        NOMBRE.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        NOMBRE.setText("Usuario:");

        AP.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        AP.setText("Fecha de Nacimiento:");

        AM.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        AM.setText("Nombre(s):");

        F_N.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        F_N.setText("Apellido P:");

        TEL.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        TEL.setText("Telefono:");

        EMAIL.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        EMAIL.setText("Dirección:");

        user.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        EMAIL1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        EMAIL1.setText("Número de Casa:");

        Guardar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Guardar.setText("Guardar");

        Cancelar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Cancelar.setText("Cancelar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(EMAIL1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Num_cas))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(TEL1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(TEL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(T_TEL))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(AM)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(EMAIL)
                                .addGap(18, 18, 18)
                                .addComponent(dir))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(AP)
                                .addGap(18, 18, 18)
                                .addComponent(FN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(F_N)
                                .addGap(18, 18, 18)
                                .addComponent(APP, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(F_N1)
                                .addGap(18, 18, 18)
                                .addComponent(APM, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(NOMBRE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(NOMBRE1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pass)))))
                .addGap(23, 23, 23))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(Guardar)
                .addGap(18, 18, 18)
                .addComponent(Cancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NOMBRE)
                    .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NOMBRE1)
                    .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AM)
                    .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(F_N)
                    .addComponent(APP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(F_N1)
                    .addComponent(APM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AP)
                    .addComponent(FN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TEL1)
                    .addComponent(Genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TEL)
                    .addComponent(T_TEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EMAIL)
                    .addComponent(dir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EMAIL1)
                    .addComponent(Num_cas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Guardar)
                    .addComponent(Cancelar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AM;
    private javax.swing.JLabel AP;
    public javax.swing.JTextField APM;
    public javax.swing.JTextField APP;
    private javax.swing.JButton Cancelar;
    private javax.swing.JLabel EMAIL;
    private javax.swing.JLabel EMAIL1;
    public com.toedter.calendar.JDateChooser FN;
    private javax.swing.JLabel F_N;
    private javax.swing.JLabel F_N1;
    public javax.swing.JComboBox Genero;
    private javax.swing.JButton Guardar;
    private javax.swing.JLabel NOMBRE;
    private javax.swing.JLabel NOMBRE1;
    public javax.swing.JTextField Num_cas;
    private javax.swing.JLabel TEL;
    private javax.swing.JLabel TEL1;
    public javax.swing.JTextField T_TEL;
    public javax.swing.JTextField dir;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField nom;
    public javax.swing.JPasswordField pass;
    public javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables

    public void controller(ControllerResident event) {
        Guardar.addActionListener(event);
        Guardar.setActionCommand("Guardar");
        Cancelar.addActionListener(event);
        Cancelar.setActionCommand("Cancelar");

        APM.addKeyListener(new Letter_Mayus());
        APP.addKeyListener(new Letter_Mayus());
        dir.addKeyListener(new Letter_Mayus());
        nom.addKeyListener(new Letter_Mayus());
        user.addKeyListener(new Letter_Mayus());

        APM.addKeyListener(new only_letters());
        APP.addKeyListener(new only_letters());
        nom.addKeyListener(new space_Letters());
        user.addKeyListener(new only_letters());
        pass.addKeyListener(new only_num());
        T_TEL.addKeyListener(new only_num());
        Num_cas.addKeyListener(new only_num());
    }
}
