/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sac_sistema_administrador_de_condominios.Interfaces;

import Codes.MySQL.MySQL;
import Controllers.Controller_Datos;
import Extras.Letter_Mayus;

/**
 *
 * @author Dany-PC
 */
public class New_Event extends javax.swing.JFrame {

    public MySQL mysql;

    /**
     * Creates new form New_Event
     *
     * @param mysql
     */
    public New_Event(MySQL mysql) {
        initComponents();
        this.mysql = mysql;
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Num_de_casas = new javax.swing.JLabel();
        Num_de_casas1 = new javax.swing.JLabel();
        Num_de_casas2 = new javax.swing.JLabel();
        Fecha = new com.toedter.calendar.JDateChooser();
        Evento = new javax.swing.JTextField();
        Cancel = new javax.swing.JButton();
        Acept = new javax.swing.JButton();
        Residentes = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nuevo Evento");
        setResizable(false);

        Num_de_casas.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Num_de_casas.setText("Fecha:");

        Num_de_casas1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Num_de_casas1.setText("Evento:");

        Num_de_casas2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Num_de_casas2.setText("Residente:");

        Fecha.setDateFormatString("yyyy-MM-d");
        Fecha.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        Evento.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        Cancel.setText("Cancelar");

        Acept.setText("Aceptar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Num_de_casas)
                        .addGap(18, 18, 18)
                        .addComponent(Fecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Num_de_casas1)
                        .addGap(18, 18, 18)
                        .addComponent(Evento, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Num_de_casas2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Cancel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Acept)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(Residentes))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Num_de_casas)
                    .addComponent(Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Num_de_casas1)
                    .addComponent(Evento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Num_de_casas2)
                    .addComponent(Residentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cancel)
                    .addComponent(Acept))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Acept;
    private javax.swing.JButton Cancel;
    public javax.swing.JTextField Evento;
    public com.toedter.calendar.JDateChooser Fecha;
    private javax.swing.JLabel Num_de_casas;
    private javax.swing.JLabel Num_de_casas1;
    private javax.swing.JLabel Num_de_casas2;
    public javax.swing.JTextField Residentes;
    // End of variables declaration//GEN-END:variables

    public void controller(Controller_Datos event) {
        
        Acept.addActionListener(event);
        Acept.setActionCommand("Acept");
        
        Cancel.addActionListener(event);
        Cancel.setActionCommand("Cancel");
        
        Evento.addKeyListener(new Letter_Mayus());
    }
}
