/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sac_sistema_administrador_de_condominios.Interfaces;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import Controllers.ControllerWindows;

/**
 *
 * @author Dany-PC
 */
public class Windows_Interfaz extends javax.swing.JFrame {

    private static final Logger LOG = Logger.getLogger(Windows_Interfaz.class.getName());

    /**
     * Creates new form Windows_Interfaz
     */
    public Windows_Interfaz() {
        initComponents();
        bitacoras2.setEnabled(false);
        setLocationRelativeTo(null);
        records.setText("Registros");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jToolBar2 = new javax.swing.JToolBar();
        session = new javax.swing.JButton();
        Dues = new javax.swing.JButton();
        Events = new javax.swing.JButton();
        finances = new javax.swing.JButton();
        records = new javax.swing.JButton();
        bitacoras2 = new javax.swing.JButton();
        Residents = new javax.swing.JButton();
        suggestions = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tb_Events = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        Bienvenido = new javax.swing.JLabel();
        User = new javax.swing.JLabel();
        Num_de_casas = new javax.swing.JLabel();
        Num_cas = new javax.swing.JLabel();
        Num_res = new javax.swing.JLabel();
        Num_de_res = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        coments = new javax.swing.JTextArea();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("SAC - Sistema Administrador de Condominios");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jToolBar2.setBackground(new java.awt.Color(102, 102, 102));
        jToolBar2.setBorder(null);
        jToolBar2.setFloatable(false);
        jToolBar2.setRollover(true);

        session.setBackground(new java.awt.Color(102, 102, 102));
        session.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        session.setText(" Sesión ");
        session.setBorder(null);
        session.setFocusable(false);
        session.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        session.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(session);

        Dues.setBackground(new java.awt.Color(102, 102, 102));
        Dues.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Dues.setText(" Cuotas");
        Dues.setBorder(null);
        Dues.setFocusable(false);
        Dues.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Dues.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(Dues);

        Events.setBackground(new java.awt.Color(102, 102, 102));
        Events.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Events.setText("  Eventos");
        Events.setBorder(null);
        Events.setFocusable(false);
        Events.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Events.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(Events);

        finances.setBackground(new java.awt.Color(102, 102, 102));
        finances.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        finances.setText("  Finanzas  ");
        finances.setBorder(null);
        finances.setFocusable(false);
        finances.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        finances.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(finances);

        records.setBackground(new java.awt.Color(102, 102, 102));
        records.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        records.setBorder(null);
        records.setFocusable(false);
        records.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        records.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(records);

        bitacoras2.setBackground(new java.awt.Color(102, 102, 102));
        bitacoras2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        bitacoras2.setText("                                                                                                                                                                       ");
        bitacoras2.setBorder(null);
        bitacoras2.setFocusable(false);
        bitacoras2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bitacoras2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(bitacoras2);

        Residents.setBackground(new java.awt.Color(102, 102, 102));
        Residents.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Residents.setText("Residentes");
        Residents.setBorder(null);
        Residents.setFocusable(false);
        Residents.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Residents.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(Residents);

        suggestions.setBackground(new java.awt.Color(102, 102, 102));
        suggestions.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        suggestions.setText("  Quejas y Sugerencias");
        suggestions.setBorder(null);
        suggestions.setFocusable(false);
        suggestions.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        suggestions.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(suggestions);

        Tb_Events.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "FECHA Y HORA", "USUARIO", "OPERACIÓN", "DESCRIPCIÓN"
            }
        ));
        Tb_Events.setEnabled(false);
        Tb_Events.setFocusable(false);
        jScrollPane1.setViewportView(Tb_Events);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Eventos del dia");

        Bienvenido.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Bienvenido.setText("Bienvenido:");

        User.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        User.setText("Usuario");

        Num_de_casas.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Num_de_casas.setText("Número de casas:");

        Num_cas.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Num_cas.setText("0");

        Num_res.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Num_res.setText("0");

        Num_de_res.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Num_de_res.setText("Número de residentes:");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3), "Comentarios del Día", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N

        coments.setColumns(20);
        coments.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        coments.setRows(5);
        coments.setAutoscrolls(false);
        coments.setEnabled(false);
        jScrollPane3.setViewportView(coments);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Bienvenido)
                        .addGap(6, 6, 6)
                        .addComponent(User)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Num_de_casas)
                        .addGap(6, 6, 6)
                        .addComponent(Num_cas)
                        .addGap(69, 69, 69)
                        .addComponent(Num_de_res)
                        .addGap(6, 6, 6)
                        .addComponent(Num_res)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Bienvenido)
                            .addComponent(User)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Num_de_casas)
                            .addComponent(Num_cas)
                            .addComponent(Num_de_res)
                            .addComponent(Num_res))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        programExit();
    }//GEN-LAST:event_formWindowClosing
    private void programExit() {
        try {
            if (JOptionPane.showConfirmDialog(null, "¿Seguro que desea salir?", "Salir", JOptionPane.YES_NO_OPTION) == 0) {
                LOG.info("Final de la Ejecucion del Programa");
                System.exit(0);
            }
        } catch (Throwable ex) {
            Logger.getLogger(Windows_Interfaz.class.getName()).log(Level.SEVERE, "Error de Confirmacion para Salir del Programa");
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bienvenido;
    public javax.swing.JButton Dues;
    public javax.swing.JButton Events;
    public javax.swing.JLabel Num_cas;
    private javax.swing.JLabel Num_de_casas;
    private javax.swing.JLabel Num_de_res;
    public javax.swing.JLabel Num_res;
    public javax.swing.JButton Residents;
    public javax.swing.JTable Tb_Events;
    public javax.swing.JLabel User;
    private javax.swing.JButton bitacoras2;
    public javax.swing.JTextArea coments;
    public javax.swing.JButton finances;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JToolBar jToolBar2;
    public javax.swing.JButton records;
    public javax.swing.JButton session;
    public javax.swing.JButton suggestions;
    // End of variables declaration//GEN-END:variables
    public void controller(ControllerWindows event) {

        session.addActionListener(event);
        session.setActionCommand("session");
        
        Dues.addActionListener(event);
        Dues.setActionCommand("Dues");
        
        Events.addActionListener(event);
        Events.setActionCommand("Events");
        
        Residents.addActionListener(event);
        Residents.setActionCommand("Residents");
        
        finances.addActionListener(event);
        finances.setActionCommand("finances");
        
        records.addActionListener(event);
        records.setActionCommand("records");
        
        suggestions.addActionListener(event);
        suggestions.setActionCommand("suggestions");
        
    }
}
